### ISSUE TITLE
install error?

### ISSUE THREAD

**Issue by andyyuan78** [tmbdev/clstm#27]
ubgpu@ubgpu:~/github/clstm$ sudo scons install
scons: Reading SConscript files ...
version daa8f08e060d6d2bc415becc32eba36c0b4de524
scons: done reading SConscript files.
scons: Building targets ...
g++ --std=c++11 -Wno-unused-result -o clstm_proto.o -c -g -O3 -finline -g -DHGVERSION=\"daa8f08e060d6d2bc415becc32eba36c0b4de524\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 clstm_proto.cc
clstm_proto.cc:18:22: fatal error: clstm.pb.h: No such file or directory
 #include "clstm.pb.h"
                      ^
compilation terminated.
scons: **\* [clstm_proto.o] Error 1
scons: building terminated because of errors.
ubgpu@ubgpu:~/github/clstm$

**Comment by tmbdev** [comment]
You probably have a clstm.pb.cc file but deleted the clstm.pb.h file. The build system doesn't catch that situation because it assumes that clstm.pb.cc is the only file created from clstm.proto; the .h file just sort of rides along.

Try running "scons -c && scons && sudo scons install"

If anybody knows how to write a better self-contained "protoc" rule, please let me know.

**Comment by adnanulhasan** [comment]
After running  scons -c && scons && sudo scons install, I'm having the following output: 
scons -c && scons && sudo scons install
scons: Reading SConscript files ...
version a636e050aff866e991e0abd27d6389c17c8d0824
scons: done reading SConscript files.
scons: Cleaning targets ...
Removed clstm.o
Removed clstm.pb.cc
Removed clstm.pb.o
Removed clstm_prefab.o
Removed clstm_proto.o
Removed clstmfilter.o
Removed ctc.o
scons: done cleaning targets.
scons: Reading SConscript files ...
version a636e050aff866e991e0abd27d6389c17c8d0824
scons: done reading SConscript files.
scons: Building targets ...
g++ --std=c++11 -Wno-unused-result -o clstm.o -c -g -O3 -finline -g -DHGVERSION=\"a636e050aff866e991e0abd27d6389c17c8d0824\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 clstm.cc
protoc(["clstm.pb.cc"], ["clstm.proto"])
g++ --std=c++11 -Wno-unused-result -o clstm.pb.o -c -g -O3 -finline -g -DHGVERSION=\"a636e050aff866e991e0abd27d6389c17c8d0824\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 clstm.pb.cc
g++ --std=c++11 -Wno-unused-result -o clstm_prefab.o -c -g -O3 -finline -g -DHGVERSION=\"a636e050aff866e991e0abd27d6389c17c8d0824\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 clstm_prefab.cc
g++ --std=c++11 -Wno-unused-result -o clstm_proto.o -c -g -O3 -finline -g -DHGVERSION=\"a636e050aff866e991e0abd27d6389c17c8d0824\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 clstm_proto.cc
g++ --std=c++11 -Wno-unused-result -o clstmfilter.o -c -g -O3 -finline -g -DHGVERSION=\"a636e050aff866e991e0abd27d6389c17c8d0824\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 clstmfilter.cc
g++ --std=c++11 -Wno-unused-result -o ctc.o -c -g -O3 -finline -g -DHGVERSION=\"a636e050aff866e991e0abd27d6389c17c8d0824\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 ctc.cc
g++ --std=c++11 -Wno-unused-result -o extras.o -c -g -O3 -finline -g -DHGVERSION=\"a636e050aff866e991e0abd27d6389c17c8d0824\" -DNODISPLAY=1 -DTHROW=throw -I/usr/include/eigen3 extras.cc
extras.cc:372:17: fatal error: png.h: No such file or directory
 #include <png.h>
                 ^
compilation terminated.
scons: **\* [extras.o] Error 1
scons: building terminated because of errors.

**Comment by tmbdev** [comment]
You need to install the PNG development libraries (libpng12-dev on Ubuntu 15.04). I had left that out of the instructions.

**Comment by andyyuan78** [comment]
scons -c && scons && sudo scons install works
