### ISSUE TITLE
clstm.load() fails to parse what clstm.save()ed

### ISSUE THREAD

**Issue by isaomatsunami** [tmbdev/clstm#43]
To enable resumed ocrtrain, I am trying to load *.clstm. but when I reload, parse error occurs with this message.

[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "clstm.NetworkProto" because it is missing required fields: kind, ninput, noutput
libc++abi.dylib: terminating

These 3 fields(kind, ninput, noutput) are not saved?

**Comment by tmbdev** [comment]
It should be working, but the Master branch is currently undergoing rapid development.

Please use "git checkout -b separate-derivs" for the older, more stable branch.

(The parameter layout will change slightly between the old and the new models; you could probably write a conversion tool, but it's probably easier just to retrain once the new release is stable.)

**Comment by isaomatsunami** [comment]
Thank you for quick reply.
Your code runs brilliantly, smoothly with small subset of Japanese kanji
characters, about 400 kinds that elementary school boys have to learn.
2500 kinds of characters is the target number for real-life ocr. That's why
I tried to write resume option.
Thanks again. I can learn a lot from your code.

**Comment by Sleemanmunk** [comment]
I am in separate-derivs and am having the same issue. 
#export maxeval=1000
#export save_every=0
export model_name=holmes
#export lrate=1e-3
#export nhidden=30
export report_every=1000
export test_every=5000
#export lstm=BIDILSTM
export testset=../../Text_Normalization/data/ocr/Holmes/clstm/by_sentence/holmes_test.tsv
export trainset=../../Text_Normalization/data/ocr/Holmes/clstm/by_sentence/holmes_train.tsv
#export ntrain=100000
export params=1
if [ $1 == test ]
then
export mode=filter
export dataset=$testset
export load=$model_name
else
export mode=train
export dataset=$trainset
export save_name=$model_name
fi
echo $mode with $model_name on $dataset
../clstmtext $dataset

First I run in train mode, then in test mode, and it fails with the error

libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "clstm.NetworkProto" because it is missing required fields: kind, ninput, noutput
EXCEPTION Invalid message
